// This file was generated by a tool. Any change may be lost. 
// Generated by ColorOptimizer 11:52:59 mercredi 4 février 2015
// Original tool written by FastFrench

// ExtrElixir12Empty : 1 colors (start 2526 => all good 23 => not in bad 1)
// ExtrGold11Empty : 0 colors (start 2628 => all good 48 => not in bad 0)
//    => the last colors for ExtrGold11Empty were killed by ../../Data\hdv9\1.PNG
// ExtrGold12Empty : 0 colors (start 2157 => all good 21 => not in bad 0)
//    => the last colors for ExtrGold12Empty were killed by ../../Data\ExtrElixir12Empty\3.PNG
// hdv10 : 2329 colors (start 2933 => all good 2933 => not in bad 2329)
// hdv7 : 61 colors (start 2720 => all good 129 => not in bad 61)
// hdv8 : 100 colors (start 3580 => all good 190 => not in bad 100)
// hdv9 : 2 colors (start 6546 => all good 2 => not in bad 2)

namespace CoC.Bot.Data.ColorList {

	public static class Data  {
		public enum Items {
			ExtrElixir12Empty,
			ExtrGold11Empty,
			ExtrGold12Empty,
			hdv10,
			hdv7,
			hdv8,
			hdv9,
		}

		// ExtrElixir12Empty has 1 colors (computed from 9 good files and 24 bad files) 
		static int[] ExtrElixir12Empty = {
			0x00604D20, // weight: 12 
			};
		static int ExtrElixir12Empty_count = 12; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// ExtrGold11Empty has 0 colors (computed from 3 good files and 30 bad files) 
		static int[] ExtrGold11Empty = {
			};
		static int ExtrGold11Empty_count = 0; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// ExtrGold12Empty has 0 colors (computed from 5 good files and 28 bad files) 
		static int[] ExtrGold12Empty = {
			};
		static int ExtrGold12Empty_count = 0; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv10 has 2329 colors (computed from 1 good files and 32 bad files) 
		static int[] hdv10 = {
			0x00403028, // weight: 15 
			0x00782420, // weight: 10 
			0x009E4038, // weight: 7 
			0x00483430, // weight: 6 
			0x00707078, // weight: 5 
			0x00483630, // weight: 5 
			0x00883430, // weight: 5 
			0x00705C58, // weight: 4 
			0x00C03C38, // weight: 4 
			0x00803430, // weight: 4 
			};
		static int hdv10_count = 65; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv7 has 61 colors (computed from 5 good files and 28 bad files) 
		static int[] hdv7 = {
			0x00F8B040, // weight: 34 
			0x00F8AA40, // weight: 32 
			0x00F8B340, // weight: 26 
			0x00F8AE40, // weight: 18 
			0x00F8B448, // weight: 16 
			0x00505C60, // weight: 15 
			0x00F8B740, // weight: 13 
			0x00946020, // weight: 10 
			0x00F8B348, // weight: 9 
			0x00586068, // weight: 9 
			};
		static int hdv7_count = 182; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv8 has 100 colors (computed from 2 good files and 31 bad files) 
		static int[] hdv8 = {
			0x00E8AC43, // weight: 6 
			0x00E8963C, // weight: 5 
			0x00AE7646, // weight: 4 
			0x009C6C40, // weight: 4 
			0x009F6B40, // weight: 4 
			0x00B17848, // weight: 4 
			0x009E6B40, // weight: 4 
			0x00906038, // weight: 4 
			0x00835522, // weight: 4 
			0x00E8A943, // weight: 4 
			};
		static int hdv8_count = 43; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv9 has 2 colors (computed from 8 good files and 25 bad files) 
		static int[] hdv9 = {
			0x0040434D, // weight: 16 
			0x0040424D, // weight: 12 
			};
		static int hdv9_count = 28; // Minimum number of pixels from that colorList that should be found on each building of this kind


		static public int[] GetColorList(Items item)
		{
			switch(item)
			{
				case Items.ExtrElixir12Empty: return ExtrElixir12Empty;
				case Items.ExtrGold11Empty: return ExtrGold11Empty;
				case Items.ExtrGold12Empty: return ExtrGold12Empty;
				case Items.hdv10: return hdv10;
				case Items.hdv7: return hdv7;
				case Items.hdv8: return hdv8;
				case Items.hdv9: return hdv9;
				default: return null;
			}
		} // GetColorList

		static public int GetColorCount(Items item)
		{
			switch(item)
			{
				case Items.ExtrElixir12Empty: return ExtrElixir12Empty_count;
				case Items.ExtrGold11Empty: return ExtrGold11Empty_count;
				case Items.ExtrGold12Empty: return ExtrGold12Empty_count;
				case Items.hdv10: return hdv10_count;
				case Items.hdv7: return hdv7_count;
				case Items.hdv8: return hdv8_count;
				case Items.hdv9: return hdv9_count;
				default: return 0;
			}
		} // GetColorCount
	}
}

