// This file was generated by a tool. Any change may be lost. 
// Generated by ColorOptimizer 10:24:17 vendredi 6 février 2015
// Original tool written by FastFrench

// ExtrElixir12Empty : 1 colors (start 2526 => all good 23 => not in bad 1)
// ExtrGold11Empty : 0 colors (start 2628 => all good 48 => not in bad 0)
//    => the last colors for ExtrGold11Empty were killed by ../../Data\hdv10\Shape 1783.png
// ExtrGold12Empty : 0 colors (start 2157 => all good 21 => not in bad 0)
//    => the last colors for ExtrGold12Empty were killed by ../../Data\ExtrElixir12Empty\3.PNG
// hdv10 : 12 colors (start 5693 => all good 32 => not in bad 12)
// hdv7 : 1 colors (start 3701 => all good 5 => not in bad 1)
// hdv8 : 11 colors (start 4517 => all good 18 => not in bad 11)
// hdv9 : 0 colors (start 6546 => all good 2 => not in bad 0)
//    => the last colors for hdv9 were killed by ../../Data\hdv10\Shape 1783.png

namespace CoC.Bot.Data.ColorList {

	public static class Data  {
		public enum Items {
			ExtrElixir12Empty,
			ExtrGold11Empty,
			ExtrGold12Empty,
			hdv10,
			hdv7,
			hdv8,
			hdv9,
		}

		// ExtrElixir12Empty has 1 colors (computed from 9 good files and 31 bad files) 
		static int[] ExtrElixir12Empty = {
			0x00604D20, // weight: 12 
			};
		static int ExtrElixir12Empty_count = 12; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// ExtrGold11Empty has 0 colors (computed from 3 good files and 37 bad files) 
		static int[] ExtrGold11Empty = {
			};
		static int ExtrGold11Empty_count = 0; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// ExtrGold12Empty has 0 colors (computed from 5 good files and 35 bad files) 
		static int[] ExtrGold12Empty = {
			};
		static int ExtrGold12Empty_count = 0; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv10 has 12 colors (computed from 3 good files and 37 bad files) 
		static int[] hdv10 = {
			0x00903838, // weight: 80 
			0x00903830, // weight: 24 
			0x00782C2D, // weight: 20 
			0x00903837, // weight: 14 
			0x00903938, // weight: 14 
			0x007A2420, // weight: 12 
			0x008F3837, // weight: 8 
			0x00792420, // weight: 5 
			0x003B2F28, // weight: 4 
			0x0042342A, // weight: 4 
			};
		static int hdv10_count = 185; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv7 has 1 colors (computed from 6 good files and 34 bad files) 
		static int[] hdv7 = {
			0x00535B63, // weight: 6 
			};
		static int hdv7_count = 6; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv8 has 11 colors (computed from 4 good files and 36 bad files) 
		static int[] hdv8 = {
			0x00AE7646, // weight: 16 
			0x00B17848, // weight: 11 
			0x00AF7748, // weight: 10 
			0x00AF7848, // weight: 9 
			0x00A16D40, // weight: 9 
			0x009C6C40, // weight: 8 
			0x00B17949, // weight: 6 
			0x00B27848, // weight: 5 
			0x00AC7446, // weight: 5 
			0x009E6A3E, // weight: 5 
			};
		static int hdv8_count = 84; // Minimum number of pixels from that colorList that should be found on each building of this kind

		// hdv9 has 0 colors (computed from 10 good files and 30 bad files) 
		static int[] hdv9 = {
			};
		static int hdv9_count = 0; // Minimum number of pixels from that colorList that should be found on each building of this kind


		static public int[] GetColorList(Items item)
		{
			switch(item)
			{
				case Items.ExtrElixir12Empty: return ExtrElixir12Empty;
				case Items.ExtrGold11Empty: return ExtrGold11Empty;
				case Items.ExtrGold12Empty: return ExtrGold12Empty;
				case Items.hdv10: return hdv10;
				case Items.hdv7: return hdv7;
				case Items.hdv8: return hdv8;
				case Items.hdv9: return hdv9;
				default: return null;
			}
		} // GetColorList

		static public int GetColorCount(Items item)
		{
			switch(item)
			{
				case Items.ExtrElixir12Empty: return ExtrElixir12Empty_count;
				case Items.ExtrGold11Empty: return ExtrGold11Empty_count;
				case Items.ExtrGold12Empty: return ExtrGold12Empty_count;
				case Items.hdv10: return hdv10_count;
				case Items.hdv7: return hdv7_count;
				case Items.hdv8: return hdv8_count;
				case Items.hdv9: return hdv9_count;
				default: return 0;
			}
		} // GetColorCount
	}
}

