//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoC.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoC.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert when Base found.
        /// </summary>
        public static string AlertWhenBaseFound {
            get {
                return ResourceManager.GetString("AlertWhenBaseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse current window.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Clash of Clans Bot for the masses....
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clash of Clans Bot.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TBC] Clash of Clans Bot.
        /// </summary>
        public static string AppTitleGeneral {
            get {
                return ResourceManager.GetString("AppTitleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archers.
        /// </summary>
        public static string Archers {
            get {
                return ResourceManager.GetString("Archers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack All Bases.
        /// </summary>
        public static string AttackAllBases {
            get {
                return ResourceManager.GetString("AttackAllBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Dead Bases.
        /// </summary>
        public static string AttackDeadBases {
            get {
                return ResourceManager.GetString("AttackDeadBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Mode.
        /// </summary>
        public static string AttackMode {
            get {
                return ResourceManager.GetString("AttackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string AttackSettings {
            get {
                return ResourceManager.GetString("AttackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack King.
        /// </summary>
        public static string AttackTheirKing {
            get {
                return ResourceManager.GetString("AttackTheirKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Queen.
        /// </summary>
        public static string AttackTheirQueen {
            get {
                return ResourceManager.GetString("AttackTheirQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Town Hall (outside).
        /// </summary>
        public static string AttackTownhall {
            get {
                return ResourceManager.GetString("AttackTownhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack using Clan Castle troops if available.
        /// </summary>
        public static string AttackUsingClanCastle {
            get {
                return ResourceManager.GetString("AttackUsingClanCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Weak Bases.
        /// </summary>
        public static string AttackWeakBases {
            get {
                return ResourceManager.GetString("AttackWeakBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloons.
        /// </summary>
        public static string Balloons {
            get {
                return ResourceManager.GetString("Balloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarians.
        /// </summary>
        public static string Barbarians {
            get {
                return ResourceManager.GetString("Barbarians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barching.
        /// </summary>
        public static string Barching {
            get {
                return ResourceManager.GetString("Barching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrack 1.
        /// </summary>
        public static string Barrack1 {
            get {
                return ResourceManager.GetString("Barrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrack 2.
        /// </summary>
        public static string Barrack2 {
            get {
                return ResourceManager.GetString("Barrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrack 3.
        /// </summary>
        public static string Barrack3 {
            get {
                return ResourceManager.GetString("Barrack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrack 4.
        /// </summary>
        public static string Barrack4 {
            get {
                return ResourceManager.GetString("Barrack4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        public static string Barracks {
            get {
                return ResourceManager.GetString("Barracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the same BehaviorCollection on multiple objects..
        /// </summary>
        public static string CannotHostBehaviorCollectionMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostBehaviorCollectionMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot host an instance of a TriggerAction in multiple TriggerCollections simultaneously. Remove it from one TriggerCollection before adding it to another..
        /// </summary>
        public static string CannotHostBehaviorMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostBehaviorMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot host an instance of a TriggerAction in multiple TriggerCollections simultaneously. Remove it from one TriggerCollection before adding it to another..
        /// </summary>
        public static string CannotHostTriggerActionMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostTriggerActionMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the same TriggerCollection on multiple objects..
        /// </summary>
        public static string CannotHostTriggerCollectionMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostTriggerCollectionMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of a trigger cannot be attached to more than one object at a time..
        /// </summary>
        public static string CannotHostTriggerMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotHostTriggerMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the boxes that you want to meet. The bot will stop at a base when it meets the conditions. If all unchecked, bot will stop if gold or elixir are met..
        /// </summary>
        public static string ConditionsMessage {
            get {
                return ResourceManager.GetString("ConditionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coords..
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Troops.
        /// </summary>
        public static string CustomTroops {
            get {
                return ResourceManager.GetString("CustomTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Barracks.
        /// </summary>
        public static string DarkBarracks {
            get {
                return ResourceManager.GetString("DarkBarracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Troops.
        /// </summary>
        public static string DarkTroops {
            get {
                return ResourceManager.GetString("DarkTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Settings.
        /// </summary>
        public static string DebugSettings {
            get {
                return ResourceManager.GetString("DebugSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid type for the TriggerType parameter. Make sure &quot;{0}&quot; derives from TriggerBase..
        /// </summary>
        public static string DefaultTriggerAttributeInvalidTriggerTypeSpecifiedExceptionMessage {
            get {
                return ResourceManager.GetString("DefaultTriggerAttributeInvalidTriggerTypeSpecifiedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay (ms).
        /// </summary>
        public static string DelayMilliseconds {
            get {
                return ResourceManager.GetString("DelayMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Settings.
        /// </summary>
        public static string DeploySettings {
            get {
                return ResourceManager.GetString("DeploySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack on all sides equally, gets most of outer base.
        /// </summary>
        public static string DeployStrategyFourSides {
            get {
                return ResourceManager.GetString("DeployStrategyFourSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack on a single side, penetrates through base.
        /// </summary>
        public static string DeployStrategyOneSide {
            get {
                return ResourceManager.GetString("DeployStrategyOneSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack on three sides, gets outer and some inside of base.
        /// </summary>
        public static string DeployStrategyThreeSides {
            get {
                return ResourceManager.GetString("DeployStrategyThreeSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack on two sides, penetrates through base.
        /// </summary>
        public static string DeployStrategyTwoSides {
            get {
                return ResourceManager.GetString("DeployStrategyTwoSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarians + Archers.
        /// </summary>
        public static string DeployTroopsBarbariansAndArchers {
            get {
                return ResourceManager.GetString("DeployTroopsBarbariansAndArchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all troops.
        /// </summary>
        public static string DeployTroopsUseAllTroops {
            get {
                return ResourceManager.GetString("DeployTroopsUseAllTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Archers.
        /// </summary>
        public static string DonateArchers {
            get {
                return ResourceManager.GetString("DonateArchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Barbarians.
        /// </summary>
        public static string DonateBarbarians {
            get {
                return ResourceManager.GetString("DonateBarbarians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Giants.
        /// </summary>
        public static string DonateGiants {
            get {
                return ResourceManager.GetString("DonateGiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot will donate the checked troops according to the specified keywords..
        /// </summary>
        public static string DonateMessage {
            get {
                return ResourceManager.GetString("DonateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateSettings {
            get {
                return ResourceManager.GetString("DonateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to All.
        /// </summary>
        public static string DonateToAll {
            get {
                return ResourceManager.GetString("DonateToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragons.
        /// </summary>
        public static string Dragons {
            get {
                return ResourceManager.GetString("Dragons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the same instance of &quot;{0}&quot; to a &quot;{1}&quot; more than once..
        /// </summary>
        public static string DuplicateItemInCollectionExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateItemInCollectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event &quot;{0}&quot; on type &quot;{1}&quot; has an incompatible signature. Make sure the event is public and satisfies the EventHandler delegate..
        /// </summary>
        public static string EventTriggerBaseInvalidEventExceptionMessage {
            get {
                return ResourceManager.GetString("EventTriggerBaseInvalidEventExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an event named &quot;{0}&quot; on type &quot;{1}&quot;..
        /// </summary>
        public static string EventTriggerCannotFindEventNameExceptionMessage {
            get {
                return ResourceManager.GetString("EventTriggerCannotFindEventNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors.
        /// </summary>
        public static string Factors {
            get {
                return ResourceManager.GetString("Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giants.
        /// </summary>
        public static string Giants {
            get {
                return ResourceManager.GetString("Giants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblins.
        /// </summary>
        public static string Goblins {
            get {
                return ResourceManager.GetString("Goblins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golems.
        /// </summary>
        public static string Golems {
            get {
                return ResourceManager.GetString("Golems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healers.
        /// </summary>
        public static string Healers {
            get {
                return ResourceManager.GetString("Healers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show BlueStacks.
        /// </summary>
        public static string HideShowBlueStacks {
            get {
                return ResourceManager.GetString("HideShowBlueStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hog Rider.
        /// </summary>
        public static string HogRider {
            get {
                return ResourceManager.GetString("HogRider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hog Riders.
        /// </summary>
        public static string HogRiders {
            get {
                return ResourceManager.GetString("HogRiders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        public static string LabelDelay {
            get {
                return ResourceManager.GetString("LabelDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Settings:.
        /// </summary>
        public static string LabelKingSettings {
            get {
                return ResourceManager.GetString("LabelKingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer:.
        /// </summary>
        public static string LabelMaxArcherTowerLevel {
            get {
                return ResourceManager.GetString("LabelMaxArcherTowerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannon:.
        /// </summary>
        public static string LabelMaxCannonLevel {
            get {
                return ResourceManager.GetString("LabelMaxCannonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. troops per request:.
        /// </summary>
        public static string LabelMaxDonationsPerRequest {
            get {
                return ResourceManager.GetString("LabelMaxDonationsPerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Town Hall:.
        /// </summary>
        public static string LabelMaximumTownhallLevel {
            get {
                return ResourceManager.GetString("LabelMaximumTownhallLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortar:.
        /// </summary>
        public static string LabelMaxMortarLevel {
            get {
                return ResourceManager.GetString("LabelMaxMortarLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Trophies:.
        /// </summary>
        public static string LabelMaxTrophies {
            get {
                return ResourceManager.GetString("LabelMaxTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard:.
        /// </summary>
        public static string LabelMaxWizardTowerLevel {
            get {
                return ResourceManager.GetString("LabelMaxWizardTowerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbow:.
        /// </summary>
        public static string LabelMaxXbowLevel {
            get {
                return ResourceManager.GetString("LabelMaxXbowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Dark Elixir:.
        /// </summary>
        public static string LabelMinimumDarkElixir {
            get {
                return ResourceManager.GetString("LabelMinimumDarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Elixir:.
        /// </summary>
        public static string LabelMinimumElixir {
            get {
                return ResourceManager.GetString("LabelMinimumElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Gold:.
        /// </summary>
        public static string LabelMinimumGold {
            get {
                return ResourceManager.GetString("LabelMinimumGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Trophy Count:.
        /// </summary>
        public static string LabelMinimumTrophyCount {
            get {
                return ResourceManager.GetString("LabelMinimumTrophyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.:.
        /// </summary>
        public static string LabelQuantity {
            get {
                return ResourceManager.GetString("LabelQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen Settings:.
        /// </summary>
        public static string LabelQueenSettings {
            get {
                return ResourceManager.GetString("LabelQueenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for:.
        /// </summary>
        public static string LabelRequestFor {
            get {
                return ResourceManager.GetString("LabelRequestFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troop:.
        /// </summary>
        public static string LabelTroop {
            get {
                return ResourceManager.GetString("LabelTroop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troop Capacity:.
        /// </summary>
        public static string LabelTroopCapacity {
            get {
                return ResourceManager.GetString("LabelTroopCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava Hound.
        /// </summary>
        public static string LavaHound {
            get {
                return ResourceManager.GetString("LavaHound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava Hounds.
        /// </summary>
        public static string LavaHounds {
            get {
                return ResourceManager.GetString("LavaHounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to take away your free [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate.
        /// </summary>
        public static string Locate {
            get {
                return ResourceManager.GetString("Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        public static string LocateBarracksManually {
            get {
                return ResourceManager.GetString("LocateBarracksManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan Castle.
        /// </summary>
        public static string LocateClanCastleManually {
            get {
                return ResourceManager.GetString("LocateClanCastleManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elixir Collectors.
        /// </summary>
        public static string LocateCollectorsManually {
            get {
                return ResourceManager.GetString("LocateCollectorsManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Barracks.
        /// </summary>
        public static string LocateDarkBarracksManually {
            get {
                return ResourceManager.GetString("LocateDarkBarracksManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Elixir Drills.
        /// </summary>
        public static string LocateDrillsManually {
            get {
                return ResourceManager.GetString("LocateDrillsManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on any to manually locate all buildings of the type, click on &apos;Done&apos; to stop the action..
        /// </summary>
        public static string LocateMessage {
            get {
                return ResourceManager.GetString("LocateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Mines.
        /// </summary>
        public static string LocateMinesManually {
            get {
                return ResourceManager.GetString("LocateMinesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate.
        /// </summary>
        public static string LocateSettings {
            get {
                return ResourceManager.GetString("LocateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &apos;Select&apos; to verify the location, click on &apos;Locate&apos; to update the location..
        /// </summary>
        public static string LocateSingleMessage {
            get {
                return ResourceManager.GetString("LocateSingleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town Hall.
        /// </summary>
        public static string LocateTownHallManually {
            get {
                return ResourceManager.GetString("LocateTownHallManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATING....
        /// </summary>
        public static string LocatingMessage {
            get {
                return ResourceManager.GetString("LocatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot fully Initialized!.
        /// </summary>
        public static string LogBotInitialized {
            get {
                return ResourceManager.GetString("LogBotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is initializing....
        /// </summary>
        public static string LogBotInitializing {
            get {
                return ResourceManager.GetString("LogBotInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Locate Controls.
        /// </summary>
        public static string ManualLocateControls {
            get {
                return ResourceManager.GetString("ManualLocateControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Level.
        /// </summary>
        public static string MaxLevel {
            get {
                return ResourceManager.GetString("MaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Dark Elixir.
        /// </summary>
        public static string MeetDarkElixir {
            get {
                return ResourceManager.GetString("MeetDarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Elixir.
        /// </summary>
        public static string MeetElixir {
            get {
                return ResourceManager.GetString("MeetElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Gold.
        /// </summary>
        public static string MeetGold {
            get {
                return ResourceManager.GetString("MeetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Town Hall Level.
        /// </summary>
        public static string MeetTownhallLevel {
            get {
                return ResourceManager.GetString("MeetTownhallLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Trophy Count.
        /// </summary>
        public static string MeetTrophyCount {
            get {
                return ResourceManager.GetString("MeetTrophyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        public static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot will continue running on the system tray.
        ///You can double click on the icon to show the window..
        /// </summary>
        public static string NotificationRunningInTray {
            get {
                return ResourceManager.GetString("NotificationRunningInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bases - Attack all that meets search.
        /// </summary>
        public static string OptionAllBases {
            get {
                return ResourceManager.GetString("OptionAllBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Bases - Meets condition, full collectors.
        /// </summary>
        public static string OptionDeadBases {
            get {
                return ResourceManager.GetString("OptionDeadBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Bases - Meets condition and able 50%.
        /// </summary>
        public static string OptionWeakBases {
            get {
                return ResourceManager.GetString("OptionWeakBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Search Settings.
        /// </summary>
        public static string OtherSearchSettings {
            get {
                return ResourceManager.GetString("OtherSearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Troops Settings.
        /// </summary>
        public static string OtherTroopsSettings {
            get {
                return ResourceManager.GetString("OtherTroopsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is starting....
        /// </summary>
        public static string OutputBotIsStarting {
            get {
                return ResourceManager.GetString("OutputBotIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping bot execution....
        /// </summary>
        public static string OutputBotIsStopping {
            get {
                return ResourceManager.GetString("OutputBotIsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot has stopped!.
        /// </summary>
        public static string OutputBotStopped {
            get {
                return ResourceManager.GetString("OutputBotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry settings changed!
        ///You need to restart BlueStacks from the agent for changes to take effect!.
        /// </summary>
        public static string OutputBSAppliedDimensionsIntoRegistry {
            get {
                return ResourceManager.GetString("OutputBSAppliedDimensionsIntoRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was a problem while applying the registry entries!.
        /// </summary>
        public static string OutputBSApplyDimensionsError {
            get {
                return ResourceManager.GetString("OutputBSApplyDimensionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying required registry entries....
        /// </summary>
        public static string OutputBSApplyDimensionsIntoRegistry {
            get {
                return ResourceManager.GetString("OutputBSApplyDimensionsIntoRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueStacks was not found!.
        /// </summary>
        public static string OutputBSNotFound {
            get {
                return ResourceManager.GetString("OutputBSNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueStacks is not set to 860x720!.
        /// </summary>
        public static string OutputBSNotRunningWithDimensions {
            get {
                return ResourceManager.GetString("OutputBSNotRunningWithDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidding BlueStacks window....
        /// </summary>
        public static string OutputHideBlueStacks {
            get {
                return ResourceManager.GetString("OutputHideBlueStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring BlueStacks window....
        /// </summary>
        public static string OutputRestoreBlueStacks {
            get {
                return ResourceManager.GetString("OutputRestoreBlueStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to locate Main Screen.
        /// </summary>
        public static string OutputTryingToLocateMainScreen {
            get {
                return ResourceManager.GetString("OutputTryingToLocateMainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ====== Welcome to {0}! ======.
        /// </summary>
        public static string OutputWelcomeMessage {
            get {
                return ResourceManager.GetString("OutputWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.E.K.K.A.
        /// </summary>
        public static string Pekka {
            get {
                return ResourceManager.GetString("Pekka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.E.K.K.As.
        /// </summary>
        public static string Pekkas {
            get {
                return ResourceManager.GetString("Pekkas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty..
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearm Infernos.
        /// </summary>
        public static string RearmInfernos {
            get {
                return ResourceManager.GetString("RearmInfernos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearm Settings.
        /// </summary>
        public static string RearmSettings {
            get {
                return ResourceManager.GetString("RearmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearm Traps.
        /// </summary>
        public static string RearmTraps {
            get {
                return ResourceManager.GetString("RearmTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearm Xbows.
        /// </summary>
        public static string RearmXbows {
            get {
                return ResourceManager.GetString("RearmXbows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Wave.
        /// </summary>
        public static string RemoveSelectedWave {
            get {
                return ResourceManager.GetString("RemoveSelectedWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot will stop when a base is found with resources higher or equal to the minimum resources..
        /// </summary>
        public static string ResourcesMessage {
            get {
                return ResourceManager.GetString("ResourcesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &quot;{0}&quot; cannot have a {3} property of type &quot;{1}&quot;. Instances of type &quot;{0}&quot; can have only a {3} property of type &quot;{2}&quot;..
        /// </summary>
        public static string RetargetedTypeConstraintViolatedExceptionMessage {
            get {
                return ResourceManager.GetString("RetargetedTypeConstraintViolatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royals and Clan Castle Settings.
        /// </summary>
        public static string RoyalsAndClanCastleSettings {
            get {
                return ResourceManager.GetString("RoyalsAndClanCastleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Bot in Search Mode Only.
        /// </summary>
        public static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchSettings {
            get {
                return ResourceManager.GetString("SearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Start to initialize the bot.
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop the Bot.
        /// </summary>
        public static string StartStopBot {
            get {
                return ResourceManager.GetString("StartStopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take snapshot of all Loots.
        /// </summary>
        public static string TakeSnapshotAllLoots {
            get {
                return ResourceManager.GetString("TakeSnapshotAllLoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take snapshot of all Towns.
        /// </summary>
        public static string TakeSnapshotAllTowns {
            get {
                return ResourceManager.GetString("TakeSnapshotAllTowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier 1.
        /// </summary>
        public static string Tier1 {
            get {
                return ResourceManager.GetString("Tier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier 2.
        /// </summary>
        public static string Tier2 {
            get {
                return ResourceManager.GetString("Tier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier 3.
        /// </summary>
        public static string Tier3 {
            get {
                return ResourceManager.GetString("Tier3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Mode.
        /// </summary>
        public static string TrainMode {
            get {
                return ResourceManager.GetString("TrainMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred troop training style from the combobox..
        /// </summary>
        public static string TrainModeMessage {
            get {
                return ResourceManager.GetString("TrainModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troop.
        /// </summary>
        public static string Troop {
            get {
                return ResourceManager.GetString("Troop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troop Request.
        /// </summary>
        public static string TroopRequest {
            get {
                return ResourceManager.GetString("TroopRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troops.
        /// </summary>
        public static string Troops {
            get {
                return ResourceManager.GetString("Troops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string TroopSettings {
            get {
                return ResourceManager.GetString("TroopSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot will use this if custom troops is selected. Troop Capacity must match!.
        /// </summary>
        public static string TroopsMessage {
            get {
                return ResourceManager.GetString("TroopsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy Settings.
        /// </summary>
        public static string TrophySettings {
            get {
                return ResourceManager.GetString("TrophySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach type &quot;{0}&quot; to type &quot;{1}&quot;. Instances of type &quot;{0}&quot; can only be attached to objects of type &quot;{2}&quot;..
        /// </summary>
        public static string TypeConstraintViolatedExceptionMessage {
            get {
                return ResourceManager.GetString("TypeConstraintViolatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Barracks.
        /// </summary>
        public static string UseBarracks {
            get {
                return ResourceManager.GetString("UseBarracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom Waves.
        /// </summary>
        public static string UseCustomWave {
            get {
                return ResourceManager.GetString("UseCustomWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valkyries.
        /// </summary>
        public static string Valkyries {
            get {
                return ResourceManager.GetString("Valkyries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Breaker.
        /// </summary>
        public static string WallBreaker {
            get {
                return ResourceManager.GetString("WallBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Breakers.
        /// </summary>
        public static string WallBreakers {
            get {
                return ResourceManager.GetString("WallBreakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waves.
        /// </summary>
        public static string Waves {
            get {
                return ResourceManager.GetString("Waves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave.
        /// </summary>
        public static string WaveSettings {
            get {
                return ResourceManager.GetString("WaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Base Settings.
        /// </summary>
        public static string WeakBaseSettings {
            get {
                return ResourceManager.GetString("WeakBaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot will attack bases that meet requirement..
        /// </summary>
        public static string WeakBaseSettingsMessage {
            get {
                return ResourceManager.GetString("WeakBaseSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witches.
        /// </summary>
        public static string Witches {
            get {
                return ResourceManager.GetString("Witches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizards.
        /// </summary>
        public static string Wizards {
            get {
                return ResourceManager.GetString("Wizards", resourceCulture);
            }
        }
    }
}
