//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoC.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoC.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert when Base found.
        /// </summary>
        public static string AlertWhenBaseFound {
            get {
                return ResourceManager.GetString("AlertWhenBaseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Clash of Clans Bot for the masses....
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clash of Clans Bot.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Settings.
        /// </summary>
        public static string AttackSettings {
            get {
                return ResourceManager.GetString("AttackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the boxes that you want to meet. The bot will stop at a base when it meets the conditions. If all unchecked, bot will stop if gold or elixir are met..
        /// </summary>
        public static string ConditionsMessage {
            get {
                return ResourceManager.GetString("ConditionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Settings.
        /// </summary>
        public static string DonateSettings {
            get {
                return ResourceManager.GetString("DonateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string GroupBoxResources {
            get {
                return ResourceManager.GetString("GroupBoxResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Trophies:.
        /// </summary>
        public static string LabelMaxTrophies {
            get {
                return ResourceManager.GetString("LabelMaxTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Dark Elixir:.
        /// </summary>
        public static string LabelMinimumDarkElixir {
            get {
                return ResourceManager.GetString("LabelMinimumDarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Elixir:.
        /// </summary>
        public static string LabelMinimumElixir {
            get {
                return ResourceManager.GetString("LabelMinimumElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Gold:.
        /// </summary>
        public static string LabelMinimumGold {
            get {
                return ResourceManager.GetString("LabelMinimumGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Trophy Count:.
        /// </summary>
        public static string LabelMinimumTrophyCount {
            get {
                return ResourceManager.GetString("LabelMinimumTrophyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Dark Elixir.
        /// </summary>
        public static string MeetDarkElixir {
            get {
                return ResourceManager.GetString("MeetDarkElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Gold and Elixir.
        /// </summary>
        public static string MeetGoldAndElixir {
            get {
                return ResourceManager.GetString("MeetGoldAndElixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Trophy Count.
        /// </summary>
        public static string MeetTrophyCount {
            get {
                return ResourceManager.GetString("MeetTrophyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Search Settings.
        /// </summary>
        public static string OtherSearchSettings {
            get {
                return ResourceManager.GetString("OtherSearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot will stop when a base is found with resources higher or equal to the minimum resources..
        /// </summary>
        public static string ResourcesMessage {
            get {
                return ResourceManager.GetString("ResourcesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mode.
        /// </summary>
        public static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        public static string SearchSettings {
            get {
                return ResourceManager.GetString("SearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troop Settings.
        /// </summary>
        public static string TroopSettings {
            get {
                return ResourceManager.GetString("TroopSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy Settings.
        /// </summary>
        public static string TrophySettings {
            get {
                return ResourceManager.GetString("TrophySettings", resourceCulture);
            }
        }
    }
}
