//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoC.Bot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int MaxTrophies {
            get {
                return ((int)(this["MaxTrophies"]));
            }
            set {
                this["MaxTrophies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80000")]
        public int MinGold {
            get {
                return ((int)(this["MinGold"]));
            }
            set {
                this["MinGold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80000")]
        public int MinElixir {
            get {
                return ((int)(this["MinElixir"]));
            }
            set {
                this["MinElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinDarkElixir {
            get {
                return ((int)(this["MinDarkElixir"]));
            }
            set {
                this["MinDarkElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinTrophyCount {
            get {
                return ((int)(this["MinTrophyCount"]));
            }
            set {
                this["MinTrophyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeetGold {
            get {
                return ((bool)(this["MeetGold"]));
            }
            set {
                this["MeetGold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeetDarkElixir {
            get {
                return ((bool)(this["MeetDarkElixir"]));
            }
            set {
                this["MeetDarkElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeetTrophyCount {
            get {
                return ((bool)(this["MeetTrophyCount"]));
            }
            set {
                this["MeetTrophyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAlertWhenBaseFound {
            get {
                return ((bool)(this["IsAlertWhenBaseFound"]));
            }
            set {
                this["IsAlertWhenBaseFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedTroopComposition {
            get {
                return ((int)(this["SelectedTroopComposition"]));
            }
            set {
                this["SelectedTroopComposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedBarrack1 {
            get {
                return ((int)(this["SelectedBarrack1"]));
            }
            set {
                this["SelectedBarrack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedBarrack2 {
            get {
                return ((int)(this["SelectedBarrack2"]));
            }
            set {
                this["SelectedBarrack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedBarrack3 {
            get {
                return ((int)(this["SelectedBarrack3"]));
            }
            set {
                this["SelectedBarrack3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedBarrack4 {
            get {
                return ((int)(this["SelectedBarrack4"]));
            }
            set {
                this["SelectedBarrack4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedAttackMode {
            get {
                return ((int)(this["SelectedAttackMode"]));
            }
            set {
                this["SelectedAttackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxCannonLevel {
            get {
                return ((int)(this["MaxCannonLevel"]));
            }
            set {
                this["MaxCannonLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxArcherTowerLevel {
            get {
                return ((int)(this["MaxArcherTowerLevel"]));
            }
            set {
                this["MaxArcherTowerLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxMortarLevel {
            get {
                return ((int)(this["MaxMortarLevel"]));
            }
            set {
                this["MaxMortarLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxWizardTowerLevel {
            get {
                return ((int)(this["MaxWizardTowerLevel"]));
            }
            set {
                this["MaxWizardTowerLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxXbowLevel {
            get {
                return ((int)(this["MaxXbowLevel"]));
            }
            set {
                this["MaxXbowLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAttackTheirKing {
            get {
                return ((bool)(this["IsAttackTheirKing"]));
            }
            set {
                this["IsAttackTheirKing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAttackTheirQueen {
            get {
                return ((bool)(this["IsAttackTheirQueen"]));
            }
            set {
                this["IsAttackTheirQueen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedDeployStrategy {
            get {
                return ((int)(this["SelectedDeployStrategy"]));
            }
            set {
                this["SelectedDeployStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedDeployTroop {
            get {
                return ((int)(this["SelectedDeployTroop"]));
            }
            set {
                this["SelectedDeployTroop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAttackTownhall {
            get {
                return ((bool)(this["IsAttackTownhall"]));
            }
            set {
                this["IsAttackTownhall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedKingAttackMode {
            get {
                return ((int)(this["SelectedKingAttackMode"]));
            }
            set {
                this["SelectedKingAttackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedQueenAttackMode {
            get {
                return ((int)(this["SelectedQueenAttackMode"]));
            }
            set {
                this["SelectedQueenAttackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAttackUsingClanCastle {
            get {
                return ((bool)(this["IsAttackUsingClanCastle"]));
            }
            set {
                this["IsAttackUsingClanCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeetElixir {
            get {
                return ((bool)(this["MeetElixir"]));
            }
            set {
                this["MeetElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeetTownhallLevel {
            get {
                return ((bool)(this["MeetTownhallLevel"]));
            }
            set {
                this["MeetTownhallLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MinTownhallLevel {
            get {
                return ((int)(this["MinTownhallLevel"]));
            }
            set {
                this["MinTownhallLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("any")]
        public string RequestTroopsMessage {
            get {
                return ((string)(this["RequestTroopsMessage"]));
            }
            set {
                this["RequestTroopsMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRequestTroops {
            get {
                return ((bool)(this["IsRequestTroops"]));
            }
            set {
                this["IsRequestTroops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giants|giant|reinforcement|any")]
        public string DonateKeywordsGiants {
            get {
                return ((string)(this["DonateKeywordsGiants"]));
            }
            set {
                this["DonateKeywordsGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wall breakers|wb|reinforcement|any")]
        public string DonateKeywordsWallBreakers {
            get {
                return ((string)(this["DonateKeywordsWallBreakers"]));
            }
            set {
                this["DonateKeywordsWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("balloons|balloon|reinforcement|any")]
        public string DonateKeywordsBalloons {
            get {
                return ((string)(this["DonateKeywordsBalloons"]));
            }
            set {
                this["DonateKeywordsBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wizards|wiz|reinforcement|any")]
        public string DonateKeywordsWizards {
            get {
                return ((string)(this["DonateKeywordsWizards"]));
            }
            set {
                this["DonateKeywordsWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("healer|reinforcement|any")]
        public string DonateKeywordsHealers {
            get {
                return ((string)(this["DonateKeywordsHealers"]));
            }
            set {
                this["DonateKeywordsHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dragon|drake|reinforcement|any")]
        public string DonateKeywordsDragons {
            get {
                return ((string)(this["DonateKeywordsDragons"]));
            }
            set {
                this["DonateKeywordsDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p.e.k.a.a|pekka|reinforcement|any")]
        public string DonateKeywordsPekkas {
            get {
                return ((string)(this["DonateKeywordsPekkas"]));
            }
            set {
                this["DonateKeywordsPekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("minions|mini|reinforcement|any")]
        public string DonateKeywordsMinions {
            get {
                return ((string)(this["DonateKeywordsMinions"]));
            }
            set {
                this["DonateKeywordsMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hog riders|hogs|bacon|reinforcement|any")]
        public string DonateKeywordsHogRiders {
            get {
                return ((string)(this["DonateKeywordsHogRiders"]));
            }
            set {
                this["DonateKeywordsHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("valkyries|valk|reinforcement|any")]
        public string DonateKeywordsValkyries {
            get {
                return ((string)(this["DonateKeywordsValkyries"]));
            }
            set {
                this["DonateKeywordsValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("golem|reinforcement|any")]
        public string DonateKeywordsGolems {
            get {
                return ((string)(this["DonateKeywordsGolems"]));
            }
            set {
                this["DonateKeywordsGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("witches|witch|reinforcement|any")]
        public string DonateKeywordsWitches {
            get {
                return ((string)(this["DonateKeywordsWitches"]));
            }
            set {
                this["DonateKeywordsWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lava hound|lava|reinforcement|any")]
        public string DonateKeywordsLavaHounds {
            get {
                return ((string)(this["DonateKeywordsLavaHounds"]));
            }
            set {
                this["DonateKeywordsLavaHounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateBarbarians {
            get {
                return ((bool)(this["IsDonateBarbarians"]));
            }
            set {
                this["IsDonateBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDonateArchers {
            get {
                return ((bool)(this["IsDonateArchers"]));
            }
            set {
                this["IsDonateArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateGoblins {
            get {
                return ((bool)(this["IsDonateGoblins"]));
            }
            set {
                this["IsDonateGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateGiants {
            get {
                return ((bool)(this["IsDonateGiants"]));
            }
            set {
                this["IsDonateGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateWallBreakers {
            get {
                return ((bool)(this["IsDonateWallBreakers"]));
            }
            set {
                this["IsDonateWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateBalloons {
            get {
                return ((bool)(this["IsDonateBalloons"]));
            }
            set {
                this["IsDonateBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateWizards {
            get {
                return ((bool)(this["IsDonateWizards"]));
            }
            set {
                this["IsDonateWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateHealers {
            get {
                return ((bool)(this["IsDonateHealers"]));
            }
            set {
                this["IsDonateHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateDragons {
            get {
                return ((bool)(this["IsDonateDragons"]));
            }
            set {
                this["IsDonateDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonatePekkas {
            get {
                return ((bool)(this["IsDonatePekkas"]));
            }
            set {
                this["IsDonatePekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateMinions {
            get {
                return ((bool)(this["IsDonateMinions"]));
            }
            set {
                this["IsDonateMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateHogRiders {
            get {
                return ((bool)(this["IsDonateHogRiders"]));
            }
            set {
                this["IsDonateHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateValkyries {
            get {
                return ((bool)(this["IsDonateValkyries"]));
            }
            set {
                this["IsDonateValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateGolems {
            get {
                return ((bool)(this["IsDonateGolems"]));
            }
            set {
                this["IsDonateGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateWitches {
            get {
                return ((bool)(this["IsDonateWitches"]));
            }
            set {
                this["IsDonateWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateLavaHounds {
            get {
                return ((bool)(this["IsDonateLavaHounds"]));
            }
            set {
                this["IsDonateLavaHounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllBarbarians {
            get {
                return ((bool)(this["IsDonateAllBarbarians"]));
            }
            set {
                this["IsDonateAllBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllArchers {
            get {
                return ((bool)(this["IsDonateAllArchers"]));
            }
            set {
                this["IsDonateAllArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllGoblins {
            get {
                return ((bool)(this["IsDonateAllGoblins"]));
            }
            set {
                this["IsDonateAllGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllGiants {
            get {
                return ((bool)(this["IsDonateAllGiants"]));
            }
            set {
                this["IsDonateAllGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllWallBreakers {
            get {
                return ((bool)(this["IsDonateAllWallBreakers"]));
            }
            set {
                this["IsDonateAllWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllBalloons {
            get {
                return ((bool)(this["IsDonateAllBalloons"]));
            }
            set {
                this["IsDonateAllBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllWizards {
            get {
                return ((bool)(this["IsDonateAllWizards"]));
            }
            set {
                this["IsDonateAllWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllHealers {
            get {
                return ((bool)(this["IsDonateAllHealers"]));
            }
            set {
                this["IsDonateAllHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllDragons {
            get {
                return ((bool)(this["IsDonateAllDragons"]));
            }
            set {
                this["IsDonateAllDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllPekkas {
            get {
                return ((bool)(this["IsDonateAllPekkas"]));
            }
            set {
                this["IsDonateAllPekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllMinions {
            get {
                return ((bool)(this["IsDonateAllMinions"]));
            }
            set {
                this["IsDonateAllMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllHogRiders {
            get {
                return ((bool)(this["IsDonateAllHogRiders"]));
            }
            set {
                this["IsDonateAllHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllValkyries {
            get {
                return ((bool)(this["IsDonateAllValkyries"]));
            }
            set {
                this["IsDonateAllValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllGolems {
            get {
                return ((bool)(this["IsDonateAllGolems"]));
            }
            set {
                this["IsDonateAllGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllWitches {
            get {
                return ((bool)(this["IsDonateAllWitches"]));
            }
            set {
                this["IsDonateAllWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDonateAllLavaHounds {
            get {
                return ((bool)(this["IsDonateAllLavaHounds"]));
            }
            set {
                this["IsDonateAllLavaHounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowPlacement {
            get {
                return ((string)(this["WindowPlacement"]));
            }
            set {
                this["WindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestArchers {
            get {
                return ((int)(this["MaxDonationsPerRequestArchers"]));
            }
            set {
                this["MaxDonationsPerRequestArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestBalloons {
            get {
                return ((int)(this["MaxDonationsPerRequestBalloons"]));
            }
            set {
                this["MaxDonationsPerRequestBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestBarbarians {
            get {
                return ((int)(this["MaxDonationsPerRequestBarbarians"]));
            }
            set {
                this["MaxDonationsPerRequestBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxDonationsPerRequestDragons {
            get {
                return ((int)(this["MaxDonationsPerRequestDragons"]));
            }
            set {
                this["MaxDonationsPerRequestDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestGiants {
            get {
                return ((int)(this["MaxDonationsPerRequestGiants"]));
            }
            set {
                this["MaxDonationsPerRequestGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestGoblins {
            get {
                return ((int)(this["MaxDonationsPerRequestGoblins"]));
            }
            set {
                this["MaxDonationsPerRequestGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxDonationsPerRequestGolems {
            get {
                return ((int)(this["MaxDonationsPerRequestGolems"]));
            }
            set {
                this["MaxDonationsPerRequestGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxDonationsPerRequestHealers {
            get {
                return ((int)(this["MaxDonationsPerRequestHealers"]));
            }
            set {
                this["MaxDonationsPerRequestHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestHogRiders {
            get {
                return ((int)(this["MaxDonationsPerRequestHogRiders"]));
            }
            set {
                this["MaxDonationsPerRequestHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxDonationsPerRequestLavaHounds {
            get {
                return ((int)(this["MaxDonationsPerRequestLavaHounds"]));
            }
            set {
                this["MaxDonationsPerRequestLavaHounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestMinions {
            get {
                return ((int)(this["MaxDonationsPerRequestMinions"]));
            }
            set {
                this["MaxDonationsPerRequestMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxDonationsPerRequestPekkas {
            get {
                return ((int)(this["MaxDonationsPerRequestPekkas"]));
            }
            set {
                this["MaxDonationsPerRequestPekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxDonationsPerRequestValkyries {
            get {
                return ((int)(this["MaxDonationsPerRequestValkyries"]));
            }
            set {
                this["MaxDonationsPerRequestValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxDonationsPerRequestWallBreakers {
            get {
                return ((int)(this["MaxDonationsPerRequestWallBreakers"]));
            }
            set {
                this["MaxDonationsPerRequestWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxDonationsPerRequestWitches {
            get {
                return ((int)(this["MaxDonationsPerRequestWitches"]));
            }
            set {
                this["MaxDonationsPerRequestWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxDonationsPerRequestWizards {
            get {
                return ((int)(this["MaxDonationsPerRequestWizards"]));
            }
            set {
                this["MaxDonationsPerRequestWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("barbarians|barbs|reinforcement|any")]
        public string DonateKeywordsBarbarians {
            get {
                return ((string)(this["DonateKeywordsBarbarians"]));
            }
            set {
                this["DonateKeywordsBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archers|arch|reinforcement|any")]
        public string DonateKeywordsArchers {
            get {
                return ((string)(this["DonateKeywordsArchers"]));
            }
            set {
                this["DonateKeywordsArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("goblins|gobs|reinforcement|any")]
        public string DonateKeywordsGoblins {
            get {
                return ((string)(this["DonateKeywordsGoblins"]));
            }
            set {
                this["DonateKeywordsGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int SelectedDarkBarrack1 {
            get {
                return ((int)(this["SelectedDarkBarrack1"]));
            }
            set {
                this["SelectedDarkBarrack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int SelectedDarkBarrack2 {
            get {
                return ((int)(this["SelectedDarkBarrack2"]));
            }
            set {
                this["SelectedDarkBarrack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TroopsQtyArchers {
            get {
                return ((int)(this["TroopsQtyArchers"]));
            }
            set {
                this["TroopsQtyArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyBarbarians {
            get {
                return ((int)(this["TroopsQtyBarbarians"]));
            }
            set {
                this["TroopsQtyBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyBalloons {
            get {
                return ((int)(this["TroopsQtyBalloons"]));
            }
            set {
                this["TroopsQtyBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyDragons {
            get {
                return ((int)(this["TroopsQtyDragons"]));
            }
            set {
                this["TroopsQtyDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int TroopsQtyGiants {
            get {
                return ((int)(this["TroopsQtyGiants"]));
            }
            set {
                this["TroopsQtyGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int TroopsQtyGoblins {
            get {
                return ((int)(this["TroopsQtyGoblins"]));
            }
            set {
                this["TroopsQtyGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyGolems {
            get {
                return ((int)(this["TroopsQtyGolems"]));
            }
            set {
                this["TroopsQtyGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TroopsQtyHealers {
            get {
                return ((int)(this["TroopsQtyHealers"]));
            }
            set {
                this["TroopsQtyHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyHogRiders {
            get {
                return ((int)(this["TroopsQtyHogRiders"]));
            }
            set {
                this["TroopsQtyHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyLavaHounds {
            get {
                return ((int)(this["TroopsQtyLavaHounds"]));
            }
            set {
                this["TroopsQtyLavaHounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyMinions {
            get {
                return ((int)(this["TroopsQtyMinions"]));
            }
            set {
                this["TroopsQtyMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyPekkas {
            get {
                return ((int)(this["TroopsQtyPekkas"]));
            }
            set {
                this["TroopsQtyPekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyValkyries {
            get {
                return ((int)(this["TroopsQtyValkyries"]));
            }
            set {
                this["TroopsQtyValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int TroopsQtyWallBreakers {
            get {
                return ((int)(this["TroopsQtyWallBreakers"]));
            }
            set {
                this["TroopsQtyWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyWitches {
            get {
                return ((int)(this["TroopsQtyWitches"]));
            }
            set {
                this["TroopsQtyWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TroopsQtyWizards {
            get {
                return ((int)(this["TroopsQtyWizards"]));
            }
            set {
                this["TroopsQtyWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseBarracks1 {
            get {
                return ((bool)(this["IsUseBarracks1"]));
            }
            set {
                this["IsUseBarracks1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseBarracks2 {
            get {
                return ((bool)(this["IsUseBarracks2"]));
            }
            set {
                this["IsUseBarracks2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseBarracks3 {
            get {
                return ((bool)(this["IsUseBarracks3"]));
            }
            set {
                this["IsUseBarracks3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseBarracks4 {
            get {
                return ((bool)(this["IsUseBarracks4"]));
            }
            set {
                this["IsUseBarracks4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseDarkBarracks1 {
            get {
                return ((bool)(this["IsUseDarkBarracks1"]));
            }
            set {
                this["IsUseDarkBarracks1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseDarkBarracks2 {
            get {
                return ((bool)(this["IsUseDarkBarracks2"]));
            }
            set {
                this["IsUseDarkBarracks2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationClanCastle {
            get {
                return ((global::System.Drawing.Point)(this["LocationClanCastle"]));
            }
            set {
                this["LocationClanCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationBarrack1 {
            get {
                return ((global::System.Drawing.Point)(this["LocationBarrack1"]));
            }
            set {
                this["LocationBarrack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationBarrack2 {
            get {
                return ((global::System.Drawing.Point)(this["LocationBarrack2"]));
            }
            set {
                this["LocationBarrack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationBarrack3 {
            get {
                return ((global::System.Drawing.Point)(this["LocationBarrack3"]));
            }
            set {
                this["LocationBarrack3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationBarrack4 {
            get {
                return ((global::System.Drawing.Point)(this["LocationBarrack4"]));
            }
            set {
                this["LocationBarrack4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationDarkBarrack1 {
            get {
                return ((global::System.Drawing.Point)(this["LocationDarkBarrack1"]));
            }
            set {
                this["LocationDarkBarrack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationDarkBarrack2 {
            get {
                return ((global::System.Drawing.Point)(this["LocationDarkBarrack2"]));
            }
            set {
                this["LocationDarkBarrack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationAllTrapsRearm {
            get {
                return ((global::System.Drawing.Point)(this["LocationAllTrapsRearm"]));
            }
            set {
                this["LocationAllTrapsRearm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationAllXbowsRearm {
            get {
                return ((global::System.Drawing.Point)(this["LocationAllXbowsRearm"]));
            }
            set {
                this["LocationAllXbowsRearm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector1 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector1"]));
            }
            set {
                this["LocationCollector1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector2 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector2"]));
            }
            set {
                this["LocationCollector2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector3 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector3"]));
            }
            set {
                this["LocationCollector3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector4 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector4"]));
            }
            set {
                this["LocationCollector4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector5 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector5"]));
            }
            set {
                this["LocationCollector5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector6 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector6"]));
            }
            set {
                this["LocationCollector6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector7 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector7"]));
            }
            set {
                this["LocationCollector7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector8 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector8"]));
            }
            set {
                this["LocationCollector8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector9 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector9"]));
            }
            set {
                this["LocationCollector9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector10 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector10"]));
            }
            set {
                this["LocationCollector10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector11 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector11"]));
            }
            set {
                this["LocationCollector11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector12 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector12"]));
            }
            set {
                this["LocationCollector12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector13 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector13"]));
            }
            set {
                this["LocationCollector13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector14 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector14"]));
            }
            set {
                this["LocationCollector14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector15 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector15"]));
            }
            set {
                this["LocationCollector15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector16 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector16"]));
            }
            set {
                this["LocationCollector16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationCollector17 {
            get {
                return ((global::System.Drawing.Point)(this["LocationCollector17"]));
            }
            set {
                this["LocationCollector17"] = value;
            }
        }
    }
}
