//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoC.Bot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int MaxTrophies {
            get {
                return ((int)(this["MaxTrophies"]));
            }
            set {
                this["MaxTrophies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80000")]
        public int MinGold {
            get {
                return ((int)(this["MinGold"]));
            }
            set {
                this["MinGold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80000")]
        public int MinElixir {
            get {
                return ((int)(this["MinElixir"]));
            }
            set {
                this["MinElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinDarkElixir {
            get {
                return ((int)(this["MinDarkElixir"]));
            }
            set {
                this["MinDarkElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinTrophyCount {
            get {
                return ((int)(this["MinTrophyCount"]));
            }
            set {
                this["MinTrophyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeetGold {
            get {
                return ((bool)(this["MeetGold"]));
            }
            set {
                this["MeetGold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeetDarkElixir {
            get {
                return ((bool)(this["MeetDarkElixir"]));
            }
            set {
                this["MeetDarkElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeetTrophyCount {
            get {
                return ((bool)(this["MeetTrophyCount"]));
            }
            set {
                this["MeetTrophyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlertWhenBaseFound {
            get {
                return ((bool)(this["AlertWhenBaseFound"]));
            }
            set {
                this["AlertWhenBaseFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int BarbariansPercent {
            get {
                return ((int)(this["BarbariansPercent"]));
            }
            set {
                this["BarbariansPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ArchersPercent {
            get {
                return ((int)(this["ArchersPercent"]));
            }
            set {
                this["ArchersPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GoblinsPercent {
            get {
                return ((int)(this["GoblinsPercent"]));
            }
            set {
                this["GoblinsPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int NumberOfGiants {
            get {
                return ((int)(this["NumberOfGiants"]));
            }
            set {
                this["NumberOfGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int NumberOfWallBreakers {
            get {
                return ((int)(this["NumberOfWallBreakers"]));
            }
            set {
                this["NumberOfWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedTroopComposition {
            get {
                return ((int)(this["SelectedTroopComposition"]));
            }
            set {
                this["SelectedTroopComposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedBarrack1 {
            get {
                return ((int)(this["SelectedBarrack1"]));
            }
            set {
                this["SelectedBarrack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedBarrack2 {
            get {
                return ((int)(this["SelectedBarrack2"]));
            }
            set {
                this["SelectedBarrack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SelectedBarrack3 {
            get {
                return ((int)(this["SelectedBarrack3"]));
            }
            set {
                this["SelectedBarrack3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SelectedBarrack4 {
            get {
                return ((int)(this["SelectedBarrack4"]));
            }
            set {
                this["SelectedBarrack4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedAttackMode {
            get {
                return ((int)(this["SelectedAttackMode"]));
            }
            set {
                this["SelectedAttackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxCannonLevel {
            get {
                return ((int)(this["MaxCannonLevel"]));
            }
            set {
                this["MaxCannonLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxArcherTowerLevel {
            get {
                return ((int)(this["MaxArcherTowerLevel"]));
            }
            set {
                this["MaxArcherTowerLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxMortarLevel {
            get {
                return ((int)(this["MaxMortarLevel"]));
            }
            set {
                this["MaxMortarLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxWizardTowerLevel {
            get {
                return ((int)(this["MaxWizardTowerLevel"]));
            }
            set {
                this["MaxWizardTowerLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxXbowLevel {
            get {
                return ((int)(this["MaxXbowLevel"]));
            }
            set {
                this["MaxXbowLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AttackTheirKing {
            get {
                return ((bool)(this["AttackTheirKing"]));
            }
            set {
                this["AttackTheirKing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AttackTheirQueen {
            get {
                return ((bool)(this["AttackTheirQueen"]));
            }
            set {
                this["AttackTheirQueen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedDeployStrategy {
            get {
                return ((int)(this["SelectedDeployStrategy"]));
            }
            set {
                this["SelectedDeployStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedDeployTroop {
            get {
                return ((int)(this["SelectedDeployTroop"]));
            }
            set {
                this["SelectedDeployTroop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AttackTownhall {
            get {
                return ((bool)(this["AttackTownhall"]));
            }
            set {
                this["AttackTownhall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedKingAttackMode {
            get {
                return ((int)(this["SelectedKingAttackMode"]));
            }
            set {
                this["SelectedKingAttackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedQueenAttackMode {
            get {
                return ((int)(this["SelectedQueenAttackMode"]));
            }
            set {
                this["SelectedQueenAttackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AttackUsingClanCastle {
            get {
                return ((bool)(this["AttackUsingClanCastle"]));
            }
            set {
                this["AttackUsingClanCastle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeetElixir {
            get {
                return ((bool)(this["MeetElixir"]));
            }
            set {
                this["MeetElixir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeetTownhallLevel {
            get {
                return ((bool)(this["MeetTownhallLevel"]));
            }
            set {
                this["MeetTownhallLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MinTownhallLevel {
            get {
                return ((int)(this["MinTownhallLevel"]));
            }
            set {
                this["MinTownhallLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("any")]
        public string RequestTroopsMessage {
            get {
                return ((string)(this["RequestTroopsMessage"]));
            }
            set {
                this["RequestTroopsMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequestTroops {
            get {
                return ((bool)(this["RequestTroops"]));
            }
            set {
                this["RequestTroops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("barbarians|barbarian|barbs|any")]
        public string DonateKeyboardsBarbarians {
            get {
                return ((string)(this["DonateKeyboardsBarbarians"]));
            }
            set {
                this["DonateKeyboardsBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archers|archer|arch|any")]
        public string DonateKeywordsArchers {
            get {
                return ((string)(this["DonateKeywordsArchers"]));
            }
            set {
                this["DonateKeywordsArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("goblins|goblin|any")]
        public string DonateKeywordsGoblins {
            get {
                return ((string)(this["DonateKeywordsGoblins"]));
            }
            set {
                this["DonateKeywordsGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("giants|giant|any")]
        public string DonateKeywordsGiants {
            get {
                return ((string)(this["DonateKeywordsGiants"]));
            }
            set {
                this["DonateKeywordsGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wall breakers|wb|any")]
        public string DonateKeywordsWallBreakers {
            get {
                return ((string)(this["DonateKeywordsWallBreakers"]));
            }
            set {
                this["DonateKeywordsWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("balloons|balloon|any")]
        public string DonateKeywordsBalloons {
            get {
                return ((string)(this["DonateKeywordsBalloons"]));
            }
            set {
                this["DonateKeywordsBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wizards|wizard|any")]
        public string DonateKeywordsWizards {
            get {
                return ((string)(this["DonateKeywordsWizards"]));
            }
            set {
                this["DonateKeywordsWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("healer|any")]
        public string DonateKeywordsHealers {
            get {
                return ((string)(this["DonateKeywordsHealers"]));
            }
            set {
                this["DonateKeywordsHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dragon|any")]
        public string DonateKeywordsDragons {
            get {
                return ((string)(this["DonateKeywordsDragons"]));
            }
            set {
                this["DonateKeywordsDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p.e.k.a.a|pekka|any")]
        public string DonateKeywordsPekkas {
            get {
                return ((string)(this["DonateKeywordsPekkas"]));
            }
            set {
                this["DonateKeywordsPekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("minions|minion|mini|any")]
        public string DonateKeywordsMinions {
            get {
                return ((string)(this["DonateKeywordsMinions"]));
            }
            set {
                this["DonateKeywordsMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hog riders|hog rider|hogs|any")]
        public string DonateKeywordsHogRiders {
            get {
                return ((string)(this["DonateKeywordsHogRiders"]));
            }
            set {
                this["DonateKeywordsHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("valkyries|valkyrie|valk|any")]
        public string DonateKeywordsValkyries {
            get {
                return ((string)(this["DonateKeywordsValkyries"]));
            }
            set {
                this["DonateKeywordsValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("golem|any")]
        public string DonateKeywordsGolems {
            get {
                return ((string)(this["DonateKeywordsGolems"]));
            }
            set {
                this["DonateKeywordsGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("witches|witch|any")]
        public string DonateKeywordsWitches {
            get {
                return ((string)(this["DonateKeywordsWitches"]));
            }
            set {
                this["DonateKeywordsWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lava hound|hound|any")]
        public string DonateKeywordsLavaHounds {
            get {
                return ((string)(this["DonateKeywordsLavaHounds"]));
            }
            set {
                this["DonateKeywordsLavaHounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateBarbarians {
            get {
                return ((bool)(this["DonateBarbarians"]));
            }
            set {
                this["DonateBarbarians"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DonateArchers {
            get {
                return ((bool)(this["DonateArchers"]));
            }
            set {
                this["DonateArchers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateGoblins {
            get {
                return ((bool)(this["DonateGoblins"]));
            }
            set {
                this["DonateGoblins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateGiants {
            get {
                return ((bool)(this["DonateGiants"]));
            }
            set {
                this["DonateGiants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateWallBreakers {
            get {
                return ((bool)(this["DonateWallBreakers"]));
            }
            set {
                this["DonateWallBreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateBalloons {
            get {
                return ((bool)(this["DonateBalloons"]));
            }
            set {
                this["DonateBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateWizards {
            get {
                return ((bool)(this["DonateWizards"]));
            }
            set {
                this["DonateWizards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateHealers {
            get {
                return ((bool)(this["DonateHealers"]));
            }
            set {
                this["DonateHealers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateDragons {
            get {
                return ((bool)(this["DonateDragons"]));
            }
            set {
                this["DonateDragons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonatePekkas {
            get {
                return ((bool)(this["DonatePekkas"]));
            }
            set {
                this["DonatePekkas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateMinions {
            get {
                return ((bool)(this["DonateMinions"]));
            }
            set {
                this["DonateMinions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateHogRiders {
            get {
                return ((bool)(this["DonateHogRiders"]));
            }
            set {
                this["DonateHogRiders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateValkyries {
            get {
                return ((bool)(this["DonateValkyries"]));
            }
            set {
                this["DonateValkyries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateGolems {
            get {
                return ((bool)(this["DonateGolems"]));
            }
            set {
                this["DonateGolems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateWitches {
            get {
                return ((bool)(this["DonateWitches"]));
            }
            set {
                this["DonateWitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DonateLavaHounds {
            get {
                return ((bool)(this["DonateLavaHounds"]));
            }
            set {
                this["DonateLavaHounds"] = value;
            }
        }
    }
}
